name = "HemiPhoto"
uuid = "eb833249-a8f7-4ae3-9d6a-d610d08ea296"
authors = ["Glenn Newnham"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
